### ISSUE TITLE
为什么交易直接就能出块成功？

### ISSUE THREAD

**Issue by xiatianlong** [citahub/cita-sdk-java#12]
合约地址：6060604052341561000f57600080fd5b60408051908101604052600b81527f68656c6c6f20776f726c640000000000000000000000000000000000000000006020820152600090805161005692916020019061005c565b506100f7565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061009d57805160ff19168380011785556100ca565b828001600101855582156100ca579182015b828111156100ca5782518255916020019190600101906100af565b506100d69291506100da565b5090565b6100f491905b808211156100d657600081556001016100e0565b90565b6102c3806101066000396000f30060606040526004361061004b5763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166320965255811461005057806393a09352146100da575b600080fd5b341561005b57600080fd5b61006361012d565b60405160208082528190810183818151815260200191508051906020019080838360005b8381101561009f578082015183820152602001610087565b50505050905090810190601f1680156100cc5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34156100e557600080fd5b61012b60046024813581810190830135806020601f820181900481020160405190810160405281815292919060208401838380828437509496506101d695505050505050565b005b6101356101ed565b60008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156101cb5780601f106101a0576101008083540402835291602001916101cb565b820191906000526020600020905b8154815290600101906020018083116101ae57829003601f168201915b505050505090505b90565b60008180516101e99291602001906101ff565b5050565b60206040519081016040526000815290565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061024057805160ff191683800117855561026d565b8280016001018555821561026d579182015b8281111561026d578251825591602001919060010190610252565b5061027992915061027d565b5090565b6101d391905b8082111561027957600081556001016102835600a165627a7a72305820086c5bf2a74080392d819fbd84ddb063f16da81bfcfa3e0d9d095fc2b99588220029

网络地址：http://121.196.200.225:1337

from:0x9866174664d0eec7988fcc223ee14f6398cd9448
to:0x5f78ee58f5900045d9149c051e12c3b401e8c4df
amount:1
txHash:0xda58810ab925c40d1eea2d60813e66fc5fccab0acda59973dc8e2b3e117fc75d

from地址是我随意生成的地址，肯定没有余额的，为什么这笔交易能直接成功？

**Comment by driftluo** [comment]
并没有成功，你用 `getTransactionReceipt` 接口看这个 txhash 0xda58810ab925c40d1eea2d60813e66fc5fccab0acda59973dc8e2b3e117fc75d，error 信息显示：
```
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0x5a3b1df0e9366b60336fce6e31638545cdfc0f77d1e3b02bf4d34372fe1f4af4",
    "blockNumber": "0x32ceb",
    "contractAddress": null,
    "cumulativeGasUsed": "0x0",
    "errorMessage": "Cost of transaction exceeds sender balance.",
    "gasUsed": "0x0",
    "logs": [
    ],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "root": null,
    "transactionHash": "0xda58810ab925c40d1eea2d60813e66fc5fccab0acda59973dc8e2b3e117fc75d",
    "transactionIndex": "0x0"
  }
}

```

**Comment by QingyangKong** [comment]
如果transactionReceipt中有errorMessage不为null该笔交易就不算成功。你说的交易直接成功是什么意思？

**Comment by QingyangKong** [comment]
一个transation不管能否入链，在发送的时候都会生成一个transaction哈希，以供查询回执。所以有transaction哈希并不能保证该交易成功。发送一笔交易，等待一段时间（比如10s），再通过transaction哈希查询transactionReceipt，如果errorMessage为空并能返回地址则说明该transaction成功了。

**Comment by xiatianlong** [comment]
请求交易回执接口返回EthGetTransactionReceipt对象，该对象有hasError()方法，事实上这个方法已经返回false了，即没有错误。我才认定为这比交易成功了。

**Comment by xiatianlong** [comment]
我发送交易返回hash后立马就调用查询回执接口发现已经有区块信息了，我认为这边交易已经被打包进区块了，即成功了。

**Comment by xiatianlong** [comment]
顺便冒昧地提一个建议，你们发布版本方便提供maven吗？

**Comment by xiatianlong** [comment]
刚刚我确认了回执中的errorMassage，确实提示了"Cost of transaction exceeds sender balance.",告诉我余额不足，那我可以认为这是判断交易是否成功的条件吗？因为我没有发现哪里有文档说明。
在这之前，我一直是认为出了区块了就算是交易成功了，当当前的区块高度大于我交易时设置的valid_until_block且还没有出块就代表交易失败了。

**Comment by QingyangKong** [comment]
EthGetTransactionReceipt并不是真正的回执，是response的一种类型。如果你是用eth_call那么response通常会返回准确信息，而sendRawTransaction的话需要得到TransactionReceipt来判断是否成功入链。

EthGetTransactionReceipt有一个方法是getTransactionReceipt()，通过getTransactionReceipt()方法得到的是Optional<TransactionReceipt>，在保证Optional<TransactionReceipt>是present的情况下得到TransactionReceipt然后通过getErrorMessage得到errorMessage。  

在两周内会发布到jcenter供maven和gradle来使用。  
关于合约部署后的transactionReceipt获取，请参考以下代码：
```
        int countForContractDeployment = 0;
        while (true) {
            Optional<TransactionReceipt> receipt = web3
                    .ethGetTransactionReceipt(deployContractTxHash)
                    .send().getTransactionReceipt();
            if (receipt.isPresent()) {
                TransactionReceipt deployTxReceipt = receipt.get();
                if (deployTxReceipt.getErrorMessage() == null) {
                    this.contractAddress = deployTxReceipt.getContractAddress();
                    System.out.println("Contract is deployed successfully.");
                    break;
                } else {
                    System.out.println("Failed to deploy smart contract. Error: "
                            + deployTxReceipt.getErrorMessage());
                    System.exit(1);
                }
            } else {
                System.out.println("Waiting for contract deployment....");
                Thread.sleep(3000);
                if (countForContractDeployment++ > 3) {
                    System.out.println("Timeout, failed to deploy contract.");
                    System.exit(1);
                }
            }
        }
```

**Comment by xiatianlong** [comment]
`非常感谢你的耐心回复，事实上我是通过如下方式获取到错误消息：

  ```
      EthGetTransactionReceipt receipt = web3j.ethGetTransactionReceipt(txHash).send();
        if (receipt.hasError()){
            logger.severe(receipt.getError().getMessage());
            return false;
        }
        TransactionReceipt transactionReceipt = receipt.getResult();
        if (!StringUtils.isEmpty(transactionReceipt.getErrorMessage())){
            logger.severe(receipt.getError().getMessage());
            return true;
        }
```
以上是伪代码，我通过返回是true或false来判断该笔交易是否成功合法。同时我还会根据getTransaction接口返回信息是否含有区块高度还判断该笔交易是否被打包入链，根据valid_until_block来判断该笔交易是否成功。


因为我看CITA文档，部署合约似乎实际上就是一笔接收方地址为0xffffffffffffffffffffffffffffffffff010001的交易，您上面贴出的代码中的deployContractTxHash实际上这是这笔交易的hash，我的理解正确吗？

**Comment by QingyangKong** [comment]
是的，deployContractTxHash是部署合约的交易哈希。  
你的代码有一个小问题就是如果你得到交易哈希立即获取TransactionReceipt的话，如果该交易没有入链，transactionReceipt即为null，这一行  
`if (!StringUtils.isEmpty(transactionReceipt.getErrorMessage())){`  
可能会有空指针异常。这也是为什么EthGetTransactionReceipt中有一个getTransactionReceipt方法把结果封装到Optional中。  
据我所知，部署合约并不是发送到一个固定地址，你能把你看到的文档贴上来吗？

**Comment by driftluo** [comment]
部署合约是令 to 地址为空，文档如下：
> to -> 交易要发送到的地址。
> 调用合约时即为被调用合约的地址，部署合约时不填写该字段。注意地址形式为 40 个十六进制字符(160 位)，前导 0 不能省略，必须补全。

**Comment by driftluo** [comment]
abi 是否需要存储是看个人的，这只是提供一个功能，让 abi 与 合约地址绑定在一起，可以实时查看

合约部署成功后，就可以调用了，调用合约用 call 方法 还是 sendRawTransaction，取决于调用函数是否有更改状态的行为，call 方法是只读的
