### ISSUE TITLE
 gradle shadowJar got exception

### ISSUE THREAD

**Issue by timmyz** [citahub/cita-sdk-java#120]
Welcome to Gradle 5.4.1!

Here are the highlights of this release:
 - Run builds with JDK12
 - New API for Incremental Tasks
 - Updates to native projects, including Swift 5 support

For more details see https://docs.gradle.org/5.4.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/cita-sdk-java/console/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating project ':console'.
> Could not get unknown property 'classesDir' for test classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 27s

**Comment by duanyytop** [comment]
Did you add `apply plugin: 'com.github.johnrengelman.shadow'` to `console/bulid.gradle` according to https://github.com/cryptape/cita-sdk-java#install ?

**Comment by duanyytop** [comment]
Thanks @timmyz .

We have solved this issue through https://github.com/cryptape/cita-sdk-java/pull/122
