### ISSUE TITLE
完成系统合约在 SDK 中的封装

### ISSUE THREAD

**Issue by nanmuxiusi** [citahub/cita-sdk-java#125]
完成组管理合约接口
https://docs.citahub.com/zh-CN/cita/system-contract-interface/group-mng 中标准的方法：newGroup，deleteGroup，updateGroupName，addAccounts，deleteAccounts，checkScope，queryGroups。

**Comment by rainchen** [comment]
@nanmuxiusi IDE 的中封装？跟 JAVA SDK 有关系？IDE 我们是指 https://github.com/cryptape/cita-ide 这个工具

**Comment by QingYanL** [comment]
这个问题的提出是：https://talk.citahub.com/t/topic/787
期望在java-sdk中完成组管理相关合约接口
分别包含如下：
newGroup(address _origin, bytes32 _name, address[] _accounts)
deleteGroup(address _origin, address _target)
updateGroupName(address _origin, address _target, bytes32 _name)
addAccounts(address _origin, address _target, address[] _accounts)
deleteAccounts(address _origin, address _target, address[] _accounts)
queryGroups() → (address[])
deleteChild(address _group, address _child)
addChild(address _group, address _child)
queryName() → (bytes32 name)
queryAccounts() → (address[] accounts)
queryInfo() → (bytes32 name , address[] accounts)
queryChild() → (address[] children)
queryChildLength() → (uint)
queryParent() → (address parent)
inGroup(address _account) → (bool)

@rainchen

**Comment by luotuo29** [comment]
麻烦确认一下deleteGroup, addAccounts, deleteAccounts, updateGroupName这几个的合约地址

**Comment by QingYanL** [comment]
0xffffffffffffffffffffffffffffffffff02000a   
组管理
@luotuo29   这几个的合约地址都是组管理
