### ISSUE TITLE
Transaction 中 value 非零时 decodeContent() 失败

### ISSUE THREAD

**Issue by chanson-chan** [citahub/cita-sdk-java#126]
- 在获取发送信息的时候 decodeContent 抛异常
```java
sdk.appGetTransactionByHash("0xabc...").send().getTransaction().decodeContent();
```
- 看了下代码, 在 `com.cryptape.cita.utils.TransactionUtil#decodeContent` 中
```java
    public static Transaction
            decodeContent(String content) throws InvalidProtocolBufferException {

        Blockchain.UnverifiedTransaction unverifiedTx
                = Blockchain.UnverifiedTransaction.parseFrom(
                ConvertStrByte.hexStringToBytes(Numeric.cleanHexPrefix(content)));

        Blockchain.Transaction blockChainTx = unverifiedTx.getTransaction();

        int version = blockChainTx.getVersion();
        String nonce = blockChainTx.getNonce();
        long quota = blockChainTx.getQuota();
        long validUntilBlock = blockChainTx.getValidUntilBlock();
        String data = bytesToHexString(blockChainTx.getData());
        String value = bytesToHexString(blockChainTx.getValue());

        ......
```
由于 value 不为零,  `String value = bytesToHexString(blockChainTx.getValue());` 返回的 value 不是 0x 开头的, 后面转换的时候当 10 进制转换报错了

**Comment by UDLD** [comment]
Thanks for your remind, we will fix it quickly.

**Comment by chanson-chan** [comment]
> Thanks for your remind, we will fix it quickly.

I found `com.cryptape.cita.protocol.core.methods.request.Transaction#to` also without '0x' prefix.

**Comment by UDLD** [comment]
At the time of the original design, `com.cryptape.cita.protocol.core.methods.request.Transaction` was no prefix. We will consider this optimization you advise. The decodeContent error has been fixed in develop branch. Thanks for you again.
