### ISSUE TITLE
show the SDK version info in test report

### ISSUE THREAD

**Issue by rainchen** [citahub/cita-sdk-java#162]
should show the SDK version info in the "Log Output" , same as the CITA system testing report.

![Screen Shot 2020-02-17 at 4 53 38 PM](https://user-images.githubusercontent.com/71397/74638698-5ecb6e00-51a7-11ea-97c6-2f9cb7504082.png)

**Comment by UDLD** [comment]
@rainchen  fixed

**Comment by rainchen** [comment]
@UDLD 
You should comment  this issue was fixed in which PR or commit.
