### ISSUE TITLE
contractAddress mustn't has 0x prefix?

### ISSUE THREAD

**Issue by rink1969** [citahub/cita-sdk-java#2]
```
Transaction tx = Transaction.createFunctionCallTransaction(
                contractAddress,
                nonce,
                this.quota,
                this.validUntilBlock,
                VERSION,
                CHAINID,
                value,
                functionCallData);
        String rawTx = tx.sign(privateKey, isEd25519AndBlake2b,false);
```
When the contractAddress has 0x prefix, something wrong, the tx can't send to the contractAddress.
After remove 0x in contractAddress, it's ok.

**Comment by QingyangKong** [comment]
@rink1969 I've tested it with [ DeployContractDemo.java ](https://github.com/cryptape/web3j/blob/develop/examples/src/main/java/org/web3j/examples/DeployContractDemo.java) and it looks tx can be sent to address whether it is with '0x' or not. Can you test it again?
