### ISSUE TITLE
getChainId should return BigInteger

### ISSUE THREAD

**Issue by rink1969** [citahub/cita-sdk-java#85]
org/nervos/appchain/protocol/core/methods/response/AppMetaData.java

> 
        public void setChainId(int chainId) {
            this.chainId = chainId;
        }

        public int getChainId() {
            if (this.version == 0) {
                return this.chainId;
            } else if (this.version == 1) {
                return Integer.parseInt(this.chainIdV1);
            } else {
                throw new IllegalArgumentException("version number can only be 1 or 2");
            }
        }

old chainId is u32
new chainIdV1 is u256
So I think getChainId should return BigInteger
or String?
Same to argument of setChainId

**Comment by QingyangKong** [comment]
@rink1969 We decide to use String for chainId in order to support u256, and I am currently working on this issue.
